package nymgoAutomation.tests.enums;

public enum WAIT_TIME {

    IMPLICITLY_WAIT_TIME,
    CORRECT_PAGE_WAIT_TIME,
    ELEMENT_WAIT_TIME,
    INITIALIZED_ELEMENT_WAIT_TIME,
    IFRAME_WAIT_TIME,
    ADMIN_TAB_WAIT_TIME;

}
